Database:
  host: 127.0.0.1
  database: database
  username: user
  password: password

Discord:
  Bot:
    Durum: true
    Token: "TOKEN"
    Prefix: "!"
  Embed:
    Title: "MineLAB Free"
    Footer: "Powered by zRooter#7295"
    Color: "GREEN"

TopGui:
  Players: 26 # Listelencek data sayısı. Max 26 sayı girilebilir.
  Title: "&c&lTop 10 Kredi Sahibi"
  ItemLore: # Kullanılabilen placeholderlar: %kredi% & %oyuncu%
    - '&eKullanıcı: &f%oyuncu%'
    - '&eKredi: &f%kredi% ⛃'
    - ''
    - '&a&n&owww.minelab.web.tr'

ProfileGui:
  Rows: 3
  Title: "&c&lProfil"
  Slots:
    'Social':
      Slot: 11
      Material: PLAYER_HEAD #PLAYER_HEAD yazıyorsa otomatik oyuncunun kafasını çeker !
      Name: '&6Sosyal Medya'
      Lore:
        - '&dInstagram: &f%instagram%'
        - '&cYouTube: &f%youtube%'
        - '&9Discord: &f%discord%'
        - '&bTwitter: &f%twitter%'
        - '&1Skype: &f%skype%'
    'Profil':
      Slot: 15
      Material: PLAYER_HEAD
      Name: '&6Profil'
      Lore:
        - '&cKullanıcı: &f%player_name%' # %player_name% PlaceholderAPI den çeker !
        - '&cKredi: &f%minelab_kredi%'