name: MineLABFree
version: '${project.version}'
main: tr.web.minelab.minelabfree.MineLABFree
depend: [ PlaceholderAPI ]
authors: [ zRooter ]
description: MineLAB Free coded with love
website: https://minelab.web.tr
