name: MineLABFree
version: '${project.version}'
main: tr.web.minelab.minelabfree.MineLABFree
depend: [ PlaceholderAPI ]
authors: [ zRooter ]
description: MineLAB Free coded with love
website: https://minelab.web.tr

commands:
  topkredi:
    aliases:
      - kreditop
      - topk
    description: En fazla kredisi olan kişiler.
  profile:
    aliases:
      - profil
      - siteprofil
      - sprofil
      - webprofil
      - webprofile
      - siteprofile
    description: Sitedeki Profilinizi GUIde gösterir
  wshop:
    aliases:
      - sitemarket
      - webshop
    description: Site Market
  kredi:
    aliases:
      - credit
    description: Kredi Komutu
